services:
  database:
    image: tugboatqa/mariadb:10.5
    commands:
      init: []
      update: []
      build: []

  webserver:
    image: tugboatqa/php:8.1-apache
    default: true
    depends: database
    commands:
      init: [ ]
      update: [ ]
      build: [ ]
